N = int(input())
if N == 0:
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print("*     *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
if N == 1:
    print("      *")
    print("      *")
    print("      *")
    print("       ")
    print("      *")
    print("      *")
    print("      *")
if N == 2:
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")
    print("*      ")
    print("*      ")
    print("*      ")
    print(" * * * ")
if N == 3:
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")
if N == 4:
    print("       ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print("       ")
if N == 5:
    print(" * * * ")
    print("*      ")
    print("*      ")
    print("*      ")
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")
if N == 6:
    print(" * * * ")
    print("*      ")
    print("*      ")
    print("*      ")
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
if N == 7:
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print("       ")
    print("      *")
    print("      *")
    print("      *")
    print("       ")
if N == 8:
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
if N == 9:
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")